---
- name: Installing nginx
  yum:
    name: nginx
    state: latest
    update_cache: yes
 
- name: Updating default config
  template:
    src: templates/default
    dest: /etc/nginx/conf.d/default
    owner: root
    group: root
    mode: 0644
  notify: Restart nginx

- name: Installing application config
  template:
    src:  templates/application.conf.j2
    dest: /etc/nginx/conf.d/application.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify: Restart nginx

