---
- name: Loops Playbook
  hosts: all
  become: yes
  vars:
    source_folder: ./MyWebSite
    destin_folder: /var/www/html
  tasks:
  - name: Say Hello to ALL
    debug: 
      msg: "Hello {{ item }}"
    loop: 
      - "Vasya"
      - "Natig"
      - "Raf"
  - name: Loop Until Example
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10 #By default 3 times
    until: output.stdout.find("ZZZZ") == false

  - name: Print Final Output
    debug:
      var: output.stdout
    
  - name: Install many packages
    yum: 
      name: "{{ item }}"
      state: latest
    with_items:
      - python
      - mc
      - tmux

  - name: Copy Homepage File to Webserver
    copy:
      src: "{{ item }}"
      dest: "{{ destin_folder }}"
      mode: 0555
    with_fileglob: "{{ source_folder }}/*.*"
