---
- hosts: app
  tasks:
    - name: Installing nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
      become: yes

    - name: Updating default config
      template:
        src: nginx/default
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: 0644
      become: yes
      notify: Restart nginx

#handlers for one-time actions   

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
      become: true

- hosts: lb
  tasks:
    - name: Intstalling nginx
      yum:
        name: nginx
        state: latest
        update_cache: yes 

    - name: Updating default config
      template:
        src: nginx/default
        dest: /etc/nginx/conf.d/default.conf
        owner: root
        group: root
        mode: 0644
      notify: Restart nginx

#handlers for one-time actions   

  handlers:
  - name: Restart nginx
    service:
      name: nginx
      state: restarted
